# Generated by Django 4.2.23 on 2025-08-14 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('compact', 'Compact')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Βενζίνη'), ('diesel', 'Πετρέλαιο')], default='petrol', max_length=20)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('extra_insurance', models.BooleanField(default=False)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Αριθμός Κυκλοφορίας')),
                ('is_rented', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.company')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requested_category', models.CharField(blank=True, max_length=20)),
                ('extra_insurance', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='imported', max_length=10)),
                ('source_email_uid', models.CharField(blank=True, max_length=120)),
                ('raw_pdf_path', models.FilePathField(blank=True, max_length=500, recursive=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.car')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rentals.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company', 'is_rented'], name='rentals_car_company_92f51e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='rentals_car_categor_c30883_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['fuel_type'], name='rentals_car_fuel_ty_fb9b7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('company', 'license_plate'), name='uniq_plate_per_company'),
        ),
    ]
