# Generated by Django 5.2.4 on 2025-08-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='extra_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
