# Generated by Django 4.2.23 on 2025-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gm_msgid',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='raw_pdf_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'status'], name='rentals_boo_company_7a1444_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='rentals_boo_created_03e73a_idx'),
        ),
    ]
