# Generated by Django 4.2.23 on 2025-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_booking_gm_msgid_alter_booking_raw_pdf_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
