# Generated by Django 4.2.23 on 2025-08-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_booking_booking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
