# Generated by Django 5.2.4 on 2025-08-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_car_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Βενζίνη'), ('diesel', 'Πετρέλαιο')], default='petrol', max_length=20),
        ),
    ]
