# Generated by Django 4.2.23 on 2025-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_booking_booking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, unique=True
            ),
        ),
    ]
