# Generated by Django 4.2.23 on 2025-08-17 13:49

from django.db import migrations


def gen_codes(apps, schema_editor):
    Booking = apps.get_model("rentals", "Booking")
    for booking in Booking.objects.filter(booking_code=""):
        booking.booking_code = f"G5{booking.id}"
        booking.save(update_fields=["booking_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0004_alter_booking_booking_code"),
    ]

    operations = [
        migrations.RunPython(gen_codes, migrations.RunPython.noop),
    ]
