# Generated by Django 5.2.4 on 2025-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_alter_car_price_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('A', 'A - Small'), ('B', 'B - Medium'), ('C', 'C - Compact')], max_length=10),
        ),
    ]
