# Generated by Django 5.2.4 on 2025-08-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('compact', 'Compact')], max_length=10),
        ),
    ]
