# Generated by Django 5.2.4 on 2025-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_car_is_rented_alter_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_trained',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
