# Generated by Django 5.2.4 on 2025-08-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_company_last_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Αριθμός Κυκλοφορίας'),
        ),
    ]
