# Generated by Django 5.2.4 on 2025-08-09 09:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_car_license_plate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('extra_insurance', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('REQUESTED', 'Αίτημα'), ('CONFIRMED', 'Κράτηση'), ('ACTIVE', 'Σε εξέλιξη'), ('COMPLETED', 'Ολοκληρώθηκε'), ('CANCELED', 'Ακυρώθηκε')], default='REQUESTED', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Αριθμός Κυκλοφορίας'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company', 'is_rented'], name='rentals_car_company_92f51e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='rentals_car_categor_c30883_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['fuel_type'], name='rentals_car_fuel_ty_fb9b7f_idx'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('company', 'license_plate'), name='uniq_plate_per_company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rentals.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.company'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['company', 'status'], name='rentals_boo_company_7a1444_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['car', 'start_date', 'end_date'], name='rentals_boo_car_id_08ef3e_idx'),
        ),
    ]
