# Generated by Django 5.2.4 on 2025-08-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_booking_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_upn', models.EmailField(help_text='Outlook account email που έδωσε consent', max_length=254)),
                ('token_json', models.JSONField(default=dict)),
                ('delta_link', models.URLField(blank=True, default='', help_text='Graph delta link για incremental sync')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outlook_conn', to='rentals.company')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=256)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='OK', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_messages', to='rentals.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'message_id'], name='rentals_imp_company_c50182_idx'), models.Index(fields=['company', 'status'], name='rentals_imp_company_e27761_idx')],
                'unique_together': {('company', 'message_id')},
            },
        ),
    ]
