# Generated by Django 5.2.4 on 2025-08-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_outlookconnection_importedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('imported', 'Εισαγόμενη'), ('active', 'Σε εξέλιξη'), ('completed', 'Ολοκληρώθηκε'), ('cancelled', 'Ακυρώθηκε')], default='imported', max_length=10),
        ),
    ]
