"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os

# 🗂️ Ρύθμιση βάσης project
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 Κλειδί ασφαλείας (μόνο για ανάπτυξη)
SECRET_KEY = 'django-insecure-pjdl22(87-+tq8syy$c70u3k0s!73vm)tbqqfs$@o=98jt8deq'

# ⚠️ Ενεργοποιημένο debug (μόνο για ανάπτυξη)
DEBUG = True

ALLOWED_HOSTS = []

# 🧩 Εγκατεστημένες εφαρμογές
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rentals',
    'recommendations',
]

# ➕ Προσθήκη integrations (μία φορά)
if "integrations" not in INSTALLED_APPS:
    INSTALLED_APPS = list(INSTALLED_APPS) + ["integrations"]

# 🛡️ Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔗 URLs
ROOT_URLCONF = 'config.urls'

# 🧠 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🔥 WSGI
WSGI_APPLICATION = 'config.wsgi.application'

# 🗃️ Βάση Δεδομένων (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔒 Έλεγχος συνθηκών κωδικών
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌍 Γλώσσα / Ώρα
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Athens'  # πιο σωστό για Ελλάδα
USE_I18N = True
USE_TZ = True

# 🧾 Static Files (CSS, JS, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'rentals', 'static')]
# (προαιρετικό για παραγωγή)
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 🔐 Ρυθμίσεις login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/select-car/'

# 📧 Email μέσω Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'carrentalsystem22@gmail.com'
EMAIL_HOST_PASSWORD = 'footplpwnwgyigtn'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FAIL_SILENTLY = True

# 🗝️ Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========== United / Outlook Integration Settings ==========

# Mock mode: δουλεύει ΧΩΡΙΣ Outlook (διαβάζει .txt/.pdf από φάκελο)
UNITED_USE_MOCK = os.getenv("UNITED_USE_MOCK", "true").lower() == "true"
# Φάκελος με mock emails (δίπλα στο manage.py)
UNITED_MOCK_DIR = os.getenv("UNITED_MOCK_DIR", "united_mock_emails")
# Η εταιρεία στο δικό σου σύστημα που θα "χρεώνεται" τις κρατήσεις της United (Company.email)
UNITED_TARGET_COMPANY_EMAIL = os.getenv("UNITED_TARGET_COMPANY_EMAIL", "")
# Προαιρετικό φίλτρο subject
UNITED_SUBJECT_KEYWORD = os.getenv("UNITED_SUBJECT_KEYWORD", "United Booking")

# ---- Microsoft Graph: ΟΝΟΜΑΤΑ ΠΟΥ ΧΡΗΣΙΜΟΠΟΙΟΥΝ ΟΙ VIEWS ----
# Μπορείς να τα θέσεις από .env
MS_GRAPH_TENANT = os.getenv("MS_GRAPH_TENANT", "common")  # ή Tenant ID (π.χ. 'xxxxxxxx-xxxx-...')
MS_GRAPH_CLIENT_ID = os.getenv("MS_GRAPH_CLIENT_ID", os.getenv("GRAPH_CLIENT_ID", ""))
MS_GRAPH_CLIENT_SECRET = os.getenv("MS_GRAPH_CLIENT_SECRET", os.getenv("GRAPH_CLIENT_SECRET", ""))
MS_GRAPH_REDIRECT_URI = os.getenv(
    "MS_GRAPH_REDIRECT_URI",
    "http://localhost:8000/integrations/outlook/callback/"
)
# Scopes για delegated flow
MS_GRAPH_SCOPES = ["offline_access", "Mail.Read"]

# Προαιρετικά φίλτρα ανάγνωσης inbox
OUTLOOK_FILTER_FROM = os.getenv("OUTLOOK_FILTER_FROM", "")  # π.χ. 'reservations@united.com'
OUTLOOK_FOLDER = os.getenv("OUTLOOK_FOLDER", "Inbox")

# Προσωρινός φάκελος για αποθήκευση PDF που έρχονται από email
IMPORT_TMP_DIR = os.path.join(BASE_DIR, "tmp_imports")
os.makedirs(IMPORT_TMP_DIR, exist_ok=True)

# ---- Παλαιά ονόματα (back-compat με παλιές ρυθμίσεις σου) ----
GRAPH_TENANT_ID = os.getenv("GRAPH_TENANT_ID", "")
GRAPH_CLIENT_ID = os.getenv("GRAPH_CLIENT_ID", MS_GRAPH_CLIENT_ID)
GRAPH_CLIENT_SECRET = os.getenv("GRAPH_CLIENT_SECRET", MS_GRAPH_CLIENT_SECRET)
GRAPH_USER_ID = os.getenv("GRAPH_USER_ID", "")  # mailbox email ή user id (δεν απαιτείται στο delegated)

# Για να μην μπλοκάρει ο Django σε τοπικά δίκτυα/ονόματα όταν κάνεις demo
ALLOWED_HOSTS = list(set(list(ALLOWED_HOSTS) + ["127.0.0.1", "localhost"]))
CSRF_TRUSTED_ORIGINS = list(set(list(globals().get("CSRF_TRUSTED_ORIGINS", [])) + ["http://127.0.0.1"]))
# ===========================================================
