"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # ← Φόρτωση .env

# 🗂️ Ρύθμιση βάσης project
BASE_DIR = Path(__file__).resolve().parent.parent

# Φόρτωση μεταβλητών περιβάλλοντος από .env (δίπλα στο manage.py)
load_dotenv(BASE_DIR / ".env")

# 🔐 Κλειδί ασφαλείας (μόνο για ανάπτυξη)
SECRET_KEY = 'django-insecure-pjdl22(87-+tq8syy$c70u3k0s!73vm)tbqqfs$@o=98jt8deq'

# ⚠️ Ενεργοποιημένο debug (μόνο για ανάπτυξη)
DEBUG = True

ALLOWED_HOSTS: list[str] = []

# 🧩 Εγκατεστημένες εφαρμογές
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps σου
    'rentals',
    'recommendations',
]

# 🛡️ Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🔗 URLs
ROOT_URLCONF = 'config.urls'

# 🧠 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # αν έχεις global templates φάκελο, πρόσθεσέ τον εδώ
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🔥 WSGI
WSGI_APPLICATION = 'config.wsgi.application'

# 🗃️ Βάση Δεδομένων (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔒 Έλεγχος συνθηκών κωδικών
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌍 Γλώσσα / Ώρα
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Athens'
USE_I18N = True
USE_TZ = True

# 🧾 Static Files
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'rentals', 'static')]  # αν δεν έχεις, άστο όπως είναι
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # για production

# 📎 Media (για τα PDF attachments)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 🔐 Ρυθμίσεις login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/select-car/'

# 📧 Email μέσω Gmail SMTP (χρησιμοποιείς ήδη app password)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'carrentalsystem22@gmail.com'
EMAIL_HOST_PASSWORD = 'footplpwnwgyigtn'  # app password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FAIL_SILENTLY = True

# 🗝️ Default primary key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Για να μην μπλοκάρει σε τοπικά δίκτυα/ονόματα όταν κάνεις demo
ALLOWED_HOSTS = list(set(list(ALLOWED_HOSTS) + ["127.0.0.1", "localhost"]))
CSRF_TRUSTED_ORIGINS = list(set(list(globals().get("CSRF_TRUSTED_ORIGINS", [])) + ["http://127.0.0.1"]))
